# config.yaml

# Where to save checkpoints and logs
save_root: "./checkpoints_54k"
run_name: "hi-neutts-finetune_5"

# Path to the pretrained model you are fine-tuning
restore_from: "neuphonic/neutts-air"  # or your local model path


# model info
codebook_size: 65536 # xcodec
max_seq_len: 2048
lr: 0.0001
lr_scheduler_type: "cosine"
warmup_ratio: 0.05

# train info
num_train_epochs: 10
per_device_train_batch_size: 4
gradient_accumulation_steps: 1   # Accumulate gradients over N steps (effective batch = 2 * 4 = 8)
max_steps: -1
logging_steps: 100
save_steps: 1000
seed: 1337